config/routes.rb
Jamesgarage::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users
  match '/signup', to: 'users#new', via: :get

  get "users/new"
  get "pictures/show"

  match '/albums/edit', to: 'albums#edit_all', as: 'album_edit_all', via: 'get'
  match '/albums/:id/change_title', to: 'albums#change_title', as: 'change_album_title', via: 'get'
  resources :albums do
    resources :pictures
  end

  match ':controller/:action/:id', to: 'pictures#destroy', as: 'picture_delete', via: 'delete'
  match ':controller/:action/:id', to: 'pictures#update_cover', as: 'picture_cover', via: 'put'
  
  get "cars_for_sale" => "albums#index"
  get "services" => "static_pages#services"
  get "contact" => "static_pages#contact"
  get "faq" => "static_pages#faq"

  root 'static_pages#services'

end

app/models/.#album.rb
alansparrow@Alans-Mac-mini.local.18610

app/models/.#picture.rb
alansparrow@Alans-Mac-mini.local.18610

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
  attr_accessible :title
  has_many :pictures, dependent: :destroy
  
  validates :title, presence: true
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id         :integer          not null, primary key
#  album_id   :integer
#  created_at :datetime
#  updated_at :datetime
#  src_link   :string(255)
#  cover_mark :boolean
#

class Picture < ActiveRecord::Base
  belongs_to :album

  before_destroy :delete_file

  def uploaded_picture=(incoming_picture)
    name = self.id.to_s + ".jpg"
    
    # create the file path
    directory = "public/images"
    path = File.join(directory, name)


    self.src_link = name

    # write the file
    File.open(path, "wb") { |f| f.write(incoming_picture.read) }
    
  end

  private

  def delete_file
    puts "Enter delete_file"
    name = self.src_link
    directory = "public/images"
    path = File.join(directory, name)
    File.delete(path);
    puts "Finish delete_file"
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :signed_in_admin, only: [:new, :edit, :create, :edit_all, :destroy, :change_title, :update]

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    
    redirect_to album_edit_all_path
  end

  def change_title
    @album = Album.find(params[:id])
  end
  
  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(params[:album])
      flash[:success] = "Album's title updated"
      redirect_to album_edit_all_path
    else
      render 'change_title'
    end
  end

  def edit_all
    @albums = Album.all
  end
  
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(:title => params[:album][:title])

    if @album.save
      redirect_to new_album_picture_path(@album)
    else
      render 'new'
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  private

  def signed_in_admin
    if !admin?
      store_location
      flash[:danger] = "Please sign in."
      redirect_to signin_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :signed_in_admin, only: [:new, :destroy, :create, :update_cover]

  def show
    @picture = Picture.find(params[:id])
    send_data @picture.data, :filename => @picture.filename, :type => @picture.content_type
  end

  def create
    @album = Album.find(params[:album_id])
    num_of_pic = @album.pictures.count

    @attachment = @album.pictures.new
    @attachment.cover_mark = false

    #save to receive id
    @attachment.save
    
    if params[:picture] && params[:picture][:picture]
      # make the first picture the album's cover
      @attachment.cover_mark = true if num_of_pic == 0

      @attachment.uploaded_picture = params[:picture][:picture]
      @attachment.save
      flash[:success] = "File has been uploaded successfully."
    else
      flash[:danger] = "You must select a file to upload."
      @attachment.delete
    end

    redirect_to new_album_picture_path(@album)

  end

  def new
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.new
  end
  
  def destroy
    @picture = Picture.find(params[:id])    
    album = @picture.album

    if @picture.cover_mark
      @picture.destroy
      new_cover = album.pictures.first
      new_cover.cover_mark = true
      new_cover.save
    else
      @picture.destroy
    end

    redirect_to edit_album_path(album)
  end

  def update_cover
    album = Picture.find(params[:id]).album

    # change cover mark's state of this old picture to false
    @old_cover = album.pictures.find_by cover_mark: true
    @old_cover.cover_mark = false
    @old_cover.save

    # set new cover
    @new_cover = album.pictures.find(params[:id])
    @new_cover.cover_mark = true
    @new_cover.save

    redirect_to edit_album_path(@new_cover.album)
  end

  private

  def signed_in_admin
    if !admin?
      store_location
      flash[:danger] = "Please sign in."
      redirect_to signin_path
    end
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "You logged in"
      sign_in user
      redirect_back_or root_path
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
      
  end

  def destroy
    flash[:success] = "You logged out"
    sign_out
    redirect_to root_path
  end  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def services
  end

  def contact
  end

  def faq
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Hi, " + @user.name + ". Your account has been created successfully!"
      redirect_to root_path
    else
      p @user.errors
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in?
    !current_user.nil?
  end

  def admin?
    if self.current_user && self.current_user.admin
      true
    else
      false
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/.#new.html.erb
alansparrow@Alans-Mac-mini.local.18610

app/views/albums/change_title.html.erb
<h1>Change album's title</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">


    <% if @album && @album.errors.any? %>
    <div class="row">
      <div class="alert alert-danger">
	<% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
	<% end %>
      </div>
    </div>
    <% end %>


    <%= form_for(@album, :html => {:multipart => true}) do |f| %>
    
    <div class="row">
      <%= f.label "Album Title" %>
    </div>
    <div class="row">
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <p></p>
    <div class="row">
      <%= f.submit "Change title", class: "btn btn-success col-md-offset-4" %>
    </div>

    <% end %>
  </div>
</div>

app/views/albums/edit.html.erb
<div class="albums">
  <h2><%= @album.title %></h2>
  <% @album.pictures.each do |p| %>
  <div class="album-thumbnail thumbnail col-xs-6 col-md-5">
    <%= link_to image_tag(p.src_link, size: "350"), "/images/" + p.src_link, class: "fancybox", rel: "fancybox" %>
    <span><%= link_to 'delete', picture_delete_path(id: p.id), method: 'delete' %> | 
      <% if p.cover_mark %>
      <p class="label label-danger">Album cover</p>
      <% else %>
      <%= link_to 'set album cover', picture_cover_path(id: p.id), method: 'put' %>
      <% end %>
    </span>

  </div>
  
  <% end %>
</div>
<div class="albums">
  <h2><%= @album.title %></h2>
  <% @album.pictures.each do |p| %>
  <div class="album-thumbnail thumbnail col-xs-6 col-md-5">
    <%= link_to image_tag(p.src_link, size: "350"), "/images/" + p.src_link, class: "fancybox", rel: "fancybox" %>
    <span><%= link_to 'delete', picture_delete_path(id: p.id), method: 'delete' %> | 
      <% if p.cover_mark %>
      <p class="label label-danger">Album cover</p>
      <% else %>
      <%= link_to 'set album cover', picture_cover_path(id: p.id), method: 'put' %>
      <% end %>
    </span>

  </div>
  
  <% end %>
</div>
<div class="albums">
  <h2><%= @album.title %></h2>
  <% @album.pictures.each do |p| %>
  <div class="album-thumbnail thumbnail col-xs-6 col-md-5">
    <%= link_to image_tag(p.src_link, size: "350"), "/images/" + p.src_link, class: "fancybox", rel: "fancybox" %>
    <span><%= link_to 'delete', picture_delete_path(id: p.id), method: 'delete' %> | 
      <% if p.cover_mark %>
      <p class="label label-danger">Album cover</p>
      <% else %>
      <%= link_to 'set album cover', picture_cover_path(id: p.id), method: 'put' %>
      <% end %>
    </span>

  </div>
  
  <% end %>
</div>

app/views/albums/edit_all.html.erb
<div class="albums">
  
  <% @albums.each do |ab| %>
  
  <div class="album-thumbnail thumbnail col-xs-6 col-md-5">
    <% if (cover = ab.pictures.find_by cover_mark: true) %>
    <%= image_tag(cover.src_link, size: "350") %>
    <% else %>
    <%= image_tag("/images/empty.png", size: "350") %>
    <% end %>
    <div><p class="album-title"><%= ab.title %></p></div>
    <div>
      <%= link_to 'delete', album_path(id: ab.id), method: 'delete', data: { confirm: "Are you sure?" } %> | 
      <%= link_to 'edit', edit_album_path(id: ab.id) %> | 
      <%= link_to 'add photo', new_album_picture_path(ab) %> | 
      <%= link_to 'change title', change_album_title_path(id: ab.id) %>

    </div>


  </div>

  <% end %>
</div>

app/views/albums/index.html.erb
<div class="albums">
  
  <% @albums.each do |ab| %>
  
  <div class="album-thumbnail col-xs-6 col-md-5">
    <%= link_to ab, :class => "thumbnail" do %>
    <% if ab.pictures.first %>
    <%= image_tag(ab.pictures.first.src_link, size: "350") %>
    <% else %>
    <%= image_tag("/images/empty.png", size: "350") %>
    <% end %>
    <p class="album-title"><%= ab.title %></p>

    <% end %>

  </div>

  <% end %>
</div>

app/views/albums/new.html.erb
<h1>Create new album</h1>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@album, :html => {:multipart => true}) do |f| %>
      
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.submit "Create my album", class: "btn btn-default" %>

    <% end %>
  </div>
</div>

app/views/albums/show.html.erb
<div class="albums">
  <h2><%= @album.title %></h2>
  <% @album.pictures.each do |p| %>
  <div class="album-thumbnail thumbnail col-xs-6 col-md-5">
    <%= link_to image_tag(p.src_link, size: "350"), "/images/" + p.src_link, class: "fancybox", rel: "fancybox" %>
  </div>
  
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by <a href="https://www.facebook.com/baotrungtn">Alan Sparrow</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div id="logo-div">
	<%= link_to "jame's garage", root_path, id: "logo" %>
      </div>
      <div id="slogan-div">
	<p>We are a full service mechanic garage and have been proudly serving the USFK community for over 30 years!</p>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

<script src="/js/jquery-1.11.0.min.js"></script>
<link rel="stylesheet" href="/css/jquery.fancybox.css">
<script src="/js/jquery.fancybox.pack.js"></script>


<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jamesgarage</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
	<aside class="col-md-3">
	  
	  <ul class="side-menu nav nav-pills nav-stacked">
	    <li><%= link_to "Home", services_path, class: "bar-menu" %></li>
	    <li><%= link_to "Cars for sales", cars_for_sale_path, class: "bar-menu" %></li>
	    <li><%= link_to "Contact Us", contact_path, class: "bar-menu" %></li>
	  <% if !admin? %>
	    <li><%= link_to "", signin_path, class: "bar-menu glyphicon glyphicon-user" %></li>
	  </ul> 
	  <% else %>
	  </ul>
	  <ul class="side-menu nav nav-pills nav-stacked">
	    <li><%= link_to "Welcome, admin", '#', class: "label label-warning bar-menu" %></li>
	    <li><%= link_to "Add new album", new_album_path %></li>
	    <li><%= link_to "Edit albums", album_edit_all_path %></li>
	    <li><%= link_to "Log out", signout_path, method: "delete" %></li>
	  </ul> 
	  <% end %>
	  
	</aside>

	<div class="col-md-9">
	  <% flash.each do |key, value| %>
	  <div class="flash-msg alert alert-<%= key %>"><%= value %></div>
	  <% end %>

      	  <%= yield %>
	</div>
      </div>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pictures/new.html.erb
<h1>Edit Album <%= @album.title %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
	<%= form_for(@picture, url: {action: "create"}, html: {class: "form-inline offset-from-top"}) do |f| %>
	<%= f.file_field :picture, class: "form-control" %>
	<%= f.submit "Upload", class: "btn btn-success btn-sm form-control" %>
	<% end %>
	
	<p></p>

	<%= form_tag edit_album_path(@album), method: "get" do %>
	<%= submit_tag "Done", class: "btn btn-primary col-md-offset-4" %>
	<% end %>

      
    </div>

  </div>


</div>

app/views/pictures/show.html.erb
<h1>Pictures#show</h1>
<p>Find me in app/views/pictures/show.html.erb</p>

app/views/static_pages/contact.html.erb
<div class="contact-us col-md-9 col-md-offset-1">
  <div class="alert alert-warning fade in">
    <dl class="dl-horizontal">
      <dt>Cell phone</dt>
      <dd>010-3742-6062</dd>
      <dt>Office</dt>
      <dd>(02) 796-6062</dd>
      <dd>(02) 797-6304</dd>
      <dt>Fax</dt>
      <dd>(02) 794-2841</dd>
      <dt>Address</dt>
      <dd>34-158, Itaewon 1-dong, Yongsan-gu, Seoul, Korea</dd>
    </dl>
  </div>
</div>

app/views/static_pages/faq.html.erb
<h1>FAQ</h1>

app/views/static_pages/home.html.erb
<h1>Home</h1>

app/views/static_pages/services.html.erb
<%= image_tag("/images/services.jpg", width: "700", height: "500",  id: "services-image") %>
<div class="contact-us col-md-7 col-md-offset-2">
  <div class="alert alert-warning fade in">
    <dl class="dl-horizontal">

      <dt>Our sevices</dt>
      <dd>Car reparing</dd>
      <dd>Used cars for sale</dd>
      <dd>Car junking</dd>
      <dd>Car consulting</dd>
    </dl>
  </div>
</div>

app/views/users/new.html.erb
<div class="row offset-from-top">
  <% if @user && @user.errors.any? %>
    <div class="row">
    <div class="alert alert-danger col-md-5 col-md-offset-3">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
    </div>
    <% end %>
  <div class="col-md-offset-4">
    <%= form_for(@user) do |f| %>
    
    <div>
      <div class="row">
	<%= f.label :name %>    
      </div>
      <div class="row">
	<%= f.text_field :name, class: "col-md-5" %>
      </div>
    </div>
    
    <div>
      <div class="row">
	<%= f.label :email %>    
      </div>
      <div class="row">
	<%= f.text_field :email, class: "col-md-5" %>
      </div>
    </div>

    <div>
      <div class="row">
	<%= f.label :password %>
      </div>
      <div class="row">
	<%= f.password_field :password, class: "col-md-5" %>
      </div>
    </div>
    
    <div>
      <div class="row">
	<%= f.label :password_confirmation, "Confirmation" %>
      </div>
      <div class="row">
	<%= f.password_field :password_confirmation, class: "col-md-5" %>
      </div>
    </div>
    
    <div>
      <div class="row">
	<p></p>
	<%= f.submit "Create account", class: "btn btn-primary col-md-offset-1 col-md-3" %>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
Hi <%= @user.name %>, <%= @user.email %>